# Generated by Django 2.1.2 on 2018-11-27 08:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='NeuralNetworkLayer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80)),
                ('index', models.IntegerField()),
                ('network', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.NeuralNetwork')),
            ],
        ),
    ]
