# Generated by Django 2.1.2 on 2018-11-27 08:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_neuralnetworklayer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='neuralnetworklayer',
            name='network',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='neural_network_layers', to='api.NeuralNetwork'),
        ),
    ]
