# Generated by Django 2.1.2 on 2018-10-23 12:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20181021_2054'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80)),
            ],
        ),
        migrations.CreateModel(
            name='DatasetCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('index', models.IntegerField()),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Category')),
            ],
        ),
        migrations.CreateModel(
            name='GradCam',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.ImageField(upload_to='images/source')),
                ('target_layer', models.IntegerField()),
                ('target_class', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='GuidedGradCam',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.ImageField(upload_to='images/source')),
                ('target_layer', models.IntegerField()),
                ('target_class', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='ImageCategoryPrediction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('index', models.IntegerField()),
                ('confidence', models.DecimalField(decimal_places=3, max_digits=3)),
            ],
        ),
        migrations.CreateModel(
            name='SaliencyMap',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.ImageField(upload_to='images/source')),
                ('target_layer', models.IntegerField()),
            ],
        ),
        migrations.RenameField(
            model_name='image',
            old_name='image',
            new_name='source',
        ),
        migrations.RemoveField(
            model_name='dataset',
            name='description',
        ),
        migrations.RemoveField(
            model_name='dataset',
            name='model_file',
        ),
        migrations.RemoveField(
            model_name='neuralnet',
            name='description',
        ),
        migrations.AddField(
            model_name='neuralnet',
            name='active',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='neuralnet',
            name='dataset',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.Dataset'),
        ),
        migrations.AddField(
            model_name='saliencymap',
            name='image',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Image'),
        ),
        migrations.AddField(
            model_name='saliencymap',
            name='network',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.NeuralNet'),
        ),
        migrations.AddField(
            model_name='imagecategoryprediction',
            name='image',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Image'),
        ),
        migrations.AddField(
            model_name='imagecategoryprediction',
            name='network',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.NeuralNet'),
        ),
        migrations.AddField(
            model_name='guidedgradcam',
            name='image',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Image'),
        ),
        migrations.AddField(
            model_name='guidedgradcam',
            name='network',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.NeuralNet'),
        ),
        migrations.AddField(
            model_name='gradcam',
            name='image',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Image'),
        ),
        migrations.AddField(
            model_name='gradcam',
            name='network',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.NeuralNet'),
        ),
        migrations.AddField(
            model_name='datasetcategory',
            name='dataset',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Dataset'),
        ),
    ]
