# Generated by Django 2.1.3 on 2018-11-25 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20181023_1229'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='source',
        ),
        migrations.AddField(
            model_name='image',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=None),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='image',
            name='imagefile',
            field=models.ImageField(default=None, upload_to='media/'),
            preserve_default=False,
        ),
    ]
