# Generated by Django 2.1.3 on 2018-11-26 16:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20181125_1737'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datasetcategory',
            name='dataset',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dataset_categories', to='api.Dataset'),
        ),
    ]
