# Generated by Django 2.1.2 on 2018-10-13 21:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dataset',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80)),
                ('description', models.CharField(max_length=255)),
                ('model_file', models.FileField(upload_to='images/source')),
            ],
        ),
        migrations.CreateModel(
            name='GradCam',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.ImageField(upload_to='images/source')),
                ('target_layer', models.IntegerField()),
                ('target_class', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='GuidedGradCam',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.ImageField(upload_to='images/source')),
                ('target_layer', models.IntegerField()),
                ('target_class', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.ImageField(upload_to='images/source')),
                ('file_name', models.CharField(max_length=80)),
                ('class_label', models.CharField(max_length=80)),
                ('class_index', models.IntegerField()),
                ('prediction', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='NeuralNet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80)),
                ('description', models.CharField(max_length=255)),
                ('active', models.BooleanField()),
                ('model_file', models.FileField(upload_to='images/source')),
                ('dataset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='media.Dataset')),
            ],
        ),
        migrations.CreateModel(
            name='SaliencyMap',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.ImageField(upload_to='images/source')),
                ('target_layer', models.IntegerField()),
                ('target_class', models.IntegerField()),
                ('image', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='media.Image')),
                ('network', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='media.NeuralNet')),
            ],
        ),
        migrations.AddField(
            model_name='guidedgradcam',
            name='image',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='media.Image'),
        ),
        migrations.AddField(
            model_name='guidedgradcam',
            name='network',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='media.NeuralNet'),
        ),
        migrations.AddField(
            model_name='gradcam',
            name='image',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='media.Image'),
        ),
        migrations.AddField(
            model_name='gradcam',
            name='network',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='media.NeuralNet'),
        ),
    ]
