# Generated by Django 2.1.2 on 2018-10-21 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('media', '0002_auto_20181014_1129'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gradcam',
            name='image',
        ),
        migrations.RemoveField(
            model_name='gradcam',
            name='network',
        ),
        migrations.RemoveField(
            model_name='guidedgradcam',
            name='image',
        ),
        migrations.RemoveField(
            model_name='guidedgradcam',
            name='network',
        ),
        migrations.RemoveField(
            model_name='saliencymap',
            name='image',
        ),
        migrations.RemoveField(
            model_name='saliencymap',
            name='network',
        ),
        migrations.AlterField(
            model_name='dataset',
            name='model_file',
            field=models.FileField(upload_to='datasets/'),
        ),
        migrations.AlterField(
            model_name='neuralnet',
            name='model_file',
            field=models.FileField(upload_to='neuralnets/'),
        ),
        migrations.DeleteModel(
            name='GradCam',
        ),
        migrations.DeleteModel(
            name='GuidedGradCam',
        ),
        migrations.DeleteModel(
            name='SaliencyMap',
        ),
    ]
