export const REQUEST_IMAGES = 'REQUEST_IMAGES';
export const RECEIVE_IMAGES = 'RECEIVE_IMAGES';
export const REJECT_IMAGES = 'REJECT_IMAGES';

export const REQUEST_NETWORK_LAYERS = 'REQUEST_NETWORK_LAYERS';
export const REJECT_NETWORK_LAYERS = 'REJECT_NETWORK_LAYERS';
export const RECEIVE_NETWORK_LAYERS = 'RECEIVE_NETWORK_LAYERS';

export const REQUEST_NETWORK_CLASSES = 'REQUEST_NETWORK_CLASSES';
export const REJECT_NETWORK_CLASSES = 'REJECT_NETWORK_CLASSES';
export const RECEIVE_NETWORK_CLASSES = 'RECEIVE_NETWORK_CLASSES';

export const REQUEST_IMAGE_UPLOAD = 'REQUEST_IMAGE_UPLOAD';
export const REJECT_IMAGE_UPLOAD = 'REJECT_IMAGE_UPLOAD';
export const RECEIVE_IMAGE_UPLOAD = 'RECEIVE_IMAGE_UPLOAD';

export const SELECT_LAYER = 'SELECT_LAYER';
export const SELECT_CLASS = 'SELECT_CLASS';
export const SELECT_IMAGE = 'SELECT_IMAGE';

export const REQUEST_IMAGE_CLASSIFICATION = 'REQUEST_IMAGE_CLASSIFICATION';
export const REJECT_IMAGE_CLASSIFICATION = 'REJECT_IMAGE_CLASSIFICATION';
export const RECEIVE_IMAGE_CLASSIFICATION = 'RECEIVE_IMAGE_CLASSIFICATION';

export const REQUEST_GRADCAM = 'REQUEST_GRADCAM';
export const REJECT_GRADCAM = 'REJECT_GRADCAM';
export const RECEIVE_GRADCAM = 'RECEIVE_GRADCAM';

export const REQUEST_GUIDED_GRADCAM = 'REQUEST_GUIDED_GRADCAM';
export const REJECT_GUIDED_GRADCAM = 'REJECT_GUIDED_GRADCAM';
export const RECEIVE_GUIDED_GRADCAM = 'RECEIVE_GUIDED_GRADCAM';

export const OPEN_MODAL = 'OPEN_MODA';
export const CLOSE_MODAL  = 'CLOSE_MODAL';