# Generated by Django 2.1.3 on 2018-11-06 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_application_banner'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='link',
            field=models.CharField(default=None, max_length=80),
        ),
    ]
